
#Datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/bookmarks?createDatabaseIfNotExist=true&serverTimezone=Africa/Douala
    username: root
    password: mysql@237
  aouth:
    client_id: bootmarks-client-id
    client_secret: bootmarks-client-secret
    tokenValidity: 9000
    refrechTokenValidity: 9000
    auth_server: http://localhost:7075/oauth/token
    resourceIds: resources-api
    signingKey: 123
    max-failled-attempts: 5
    lock-time: 1
  mail:
    username: ghislainck7@gmail.com
    password: itijbkrnacnwrndf

bookmarks:
  admin-email: ghislainck7@gmail.com
  password: BookmarksStore@237

cron-jop: 0 0/1 * 1/1 * ?

