
#Datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://td5l74lo6615qq42.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/t1fk31jiq2mc9a2a
    username: h5b4g6dkq0w3gjli
    password: wtvxfecp1054t32a
  flyway:
    enabled: true
    user: h5b4g6dkq0w3gjli
    password: wtvxfecp1054t32a
  aouth:
    client_id: bootmarks-client-id
    client_secret: bootmarks-client-secret
    tokenValidity: 9000
    refrechTokenValidity: 9000
    auth_server: https://bookmarks-rest-api-v0.herokuapp.com:7075/oauth/token
    resourceIds: resources-api
    signingKey: 123
    max-failled-attempts: 5
    lock-time: 5
  mail:
    username: ghislainck7@gmail.com
    password: itijbkrnacnwrndf

  bookmarks:
    admin-email: ghislainck7@gmail.com
    password: BookmarksStore@237
    ui_base_url: http://localhost:4200

