#Datasource configuration
spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: quick poll
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/quick_polls?createDatabaseIfNotExist=true&serverTimezone=Africa/Douala
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql@237
server:
  port: 7075