#Datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://pxukqohrckdfo4ty.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/hhxpr5dqvq6o1i39
    username: jwrloe52fejelin8
    password: s79rti7kktg4m8l2
  flyway:
    enabled: true
    user: jwrloe52fejelin8
    password: s79rti7kktg4m8l2
  aouth:
    client_id: bootmarks-client-id
    client_secret: bootmarks-client-secret
    tokenValidity: 10000
    refrechTokenValidity: 10000
    auth_server: https://bookmarks-api-v1.herokuapp.com/oauth/token
    resourceIds: resources-api
    signingKey: 123
    max-failled-attempts: 5
    lock-time: 5
  mail:
    username: ghislainck7@gmail.com
    password: itijbkrnacnwrndf

  bookmarks:
    admin-email: ghislainck7@gmail.com
    password: BookmarksStore@237
    ui_base_url: https://bookmarks-ui.herokuapp.com

server:
  port: ${PORT:8080}


