#Datasource configuration
spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: Bookmarks Store
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/bookmarks?createDatabaseIfNotExist=true&serverTimezone=Africa/Douala
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql@237
  flyway:
    enabled: true
    user: root
    password: mysql@237
  aouth:
    client_id: bootmarks-client-id
    client_secret: bootmarks-client-secret
    tokenValidity: 9000
    refrechTokenValidity: 9000
    auth_server: http://localhost:7075/oauth/token
    resourceIds: resources-api
    signingKey: 123
    max-failled-attempts: 3
    lock-time: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: test123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  boot:
    admin:
      client:
        url: [http://localhost:8085]
        username: admin
        password: admin
#        instance:
#          metadata:
#            user:
#              name: ${spring.security.user.name}
#              password: ${spring.security.user.password}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
bookmarks:
  admin-email: ghislainck7@gmail.com
  password: BookmarksStore@237
  ui_base_url: https://i.ibb.co/937KNHR/70581610129545659.png
  icon_link: https://i.ibb.co/937KNHR/70581610129545659.png
  expiration_token: 600;

cron-jop: 0 0/1 * 1/1 * ?

